### ISSUE TITLE
Pretrained model isn't available.

### ISSUE THREAD

**Issue by Lineark** [Atenrev/chessformers#1]
It says: Download the pre-trained model from here: https://drive.google.com/file/d/1dFunGXq8bXRW0_Y47yxE4S30cU8wyfOl/view?usp=sharing
But the path shows file not exists. Could you please update the link now? I need the pretrained model. Thanks.

**Comment by Atenrev** [comment]
Currently, I do not have physical access to the original model. I will reupload the model when I have access again.

**Comment by rs545837** [comment]
Hey @Atenrev did you get the access for the model yet?

**Comment by Atenrev** [comment]
@rs545837 @Lineark Perfect timing! Thanks for reminding me, I've updated the url.

**Comment by rs545837** [comment]
Hey @Atenrev is the model in working condition or  does it give errors on running like this?
<img width="320" alt="Screenshot 2024-03-15 at 12 06 44 PM" src="https://github.com/Atenrev/chessformers/assets/114828377/83106e87-6d06-4efd-8c38-7ae2d8eaa91d">

**Comment by Atenrev** [comment]
I just checked on my computer and it's working fine. Could you check what's the exception with the debugger, please?

**Comment by rs545837** [comment]
Yeah, it's working. Did you also did analysis of your model back when you made it.
